### ISSUE TITLE
Docs state incorrect field for defining a templates directoru

### ISSUE THREAD

**Issue by Mo0rBy** [epwalsh/obsidian.nvim#569] opened 2024-05-02 17:30 UTC
### 📚 The doc issue

Was following the main README.md when setting up the plugin, specifically trying to setup templates.
[Here](https://github.com/epwalsh/obsidian.nvim?tab=readme-ov-file#using-templates) is a link to the section I am referring to.

The docs state that the `folder` attribute is used, but the correct attribute is `subdir`

### Suggest a potential alternative/fix

Just need to change the example code block from this:
```lua
{
  -- other fields ...

  templates = {
      folder = "my-templates-folder",
      date_format = "%Y-%m-%d-%a",
      time_format = "%H:%M",
  },
}
```
To this:
```lua
{
  -- other fields ...

  templates = {
      subdir = "my-templates-folder",
      date_format = "%Y-%m-%d-%a",
      time_format = "%H:%M",
  },
}
```

**Comment by Mo0rBy** [comment] 2024-05-02 17:31
The same correction needs to be made in the much larger code block example at the top of the [Configuration](https://github.com/epwalsh/obsidian.nvim?tab=readme-ov-file#configuration-options) section.

**Comment by epwalsh** [comment] 2024-05-02 17:33
Duplicate of #568, this was a recent change.

**Closed by epwalsh** 2024-05-02 17:33 UTC
Labels: documentation

**Comment by Mo0rBy** [comment] 2024-05-02 21:08
Ah I probably should've had a search first, I was in a rush.
I notice that the linked issue states that `folder` is new and that `sub_dir` is used for backwards compatibility, but using `folder` didn't work for me at all.

**Comment by epwalsh** [comment] 2024-05-02 21:11
@Mo0rBy can you show me the output of `:ObsidianDebug`?

**Comment by Mo0rBy** [comment] 2024-05-02 21:21
Ah I was running v3.7.10, just updated to v3.7.12. 
You must be very active in development! I only discovered and installed this plugin in the last few days!
