### ISSUE TITLE
Use a specific template with daily or new note?

### ISSUE THREAD

**Issue by curtbushko** [epwalsh/obsidian.nvim#163] opened 2023-08-02 15:00 UTC
### 🚀 The feature, motivation and pitch

Other than using :ObsidianTemplate and inserting a template, is there a way to create a new daily or note from a template?

**Comment by epwalsh** [comment] 2023-08-03 14:58
At the moment no, we don't have a feature for automatically inserting a template on new note creation. But that would be nice to have.

**Comment by lucidph3nx** [comment] 2023-08-05 02:09
I noticed as well, that when opening a new daily note, it adds a title in the format `# %w+ %d+' and I couldn't see a way in the code to change this using configuration.

A workaround is possible to delete the default line and run `:ObsidianTemplate example_daily_template.md` with an autocommand on opening of any new buffer that is empty except for this line.

code looks like this:
```lua
    local augroup = vim.api.nvim_create_augroup('yourname_obsidian', {})
    vim.api.nvim_create_autocmd('BufEnter', {
      group = augroup,
      pattern = '*.md',
        callback = function()
            local bufnr = vim.api.nvim_get_current_buf()
            local buffer_content = vim.api.nvim_buf_get_lines(bufnr, 0, 1, false)
            -- Check if the buffer content matches the default line format
            if #buffer_content > 0 and buffer_content[1]:match('^# %w+ %d+, %d+$') then
                -- Delete the default line
                vim.api.nvim_buf_set_lines(bufnr, 0, 1, false, {})
                -- Run ObsidianTemplate command
                vim.cmd('ObsidianTemplate example_daily_template.md')
            end
        end,
    })
```

might not be the prettiest solution, but for anyone who doesn't deal with any other files matching this starting point, it seems to work quite well. I don't tend to use templates with other kinds of notes this broadly, but maybe this works as a starting point for anyone looking to implement something like that.

**Comment by MunsMan** [comment] 2023-09-15 17:47
I'm missing the automated template insertion into daily notes as well. I will look into it over the weekend. 
I would probably add an option to the config, to link the daily note to the wanted template, and if `nil` is provided, none
is used.

I would love to have some more template variables. Would that be a new Feature request? 
What are your thoughts on adding a table for custom template variables?
Then it can just be looped and replaced.

**Comment by MunsMan** [comment] 2023-09-16 12:25
I just noticed that this might be a duplicate of #12

**Comment by epwalsh** [comment] 2023-09-20 16:07
> What are your thoughts on adding a table for custom template variables?

That would be pretty cool. I'm thinking a table of `pattern -> function` where the function takes the pattern and returns a string to replace?

**Comment by MunsMan** [comment] 2023-09-21 13:20
Yes, exactly. That is more, or less, what I already added to #195. I will look into your comments today.

**Closed** 2023-09-21 22:13 UTC
Labels: contributions welcome, feature request
