### ISSUE TITLE
Cannot run any commands

### ISSUE THREAD

**Issue by zachy-ho** [epwalsh/obsidian.nvim#10] opened 2022-09-13 08:16 UTC
### 🐛 Describe the bug

I can't seem to run any of the commands (i.e. `:ObsidianToday`, `:ObsidianOpen`, `:ObsidianBacklinks`. I'm running on macOS

I'm using [packer](https://github.com/wbthomason/packer.nvim) as my plugin management.
```lua
packer.startup({
  function(use)
    -- ... other plugins (including plenary)

    use({
      "epwalsh/obsidian.nvim",
      config = function()
        -- just my own wrapper to catch errors if `require('some plugin')` fails, it works
        local obsidian = safe_require("obsidian")
        if not obsidian then
            return
        end

        obsidian.setup({
            dir = "~/zachyho-gits/obsidian_vault",
            completion = {
                nvim_cmp = true,
            },
        })
      end,
    })
  end
})
```

### Versions

NVIM v0.8.0-dev-1074-ga48e42a29-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by zacharyho@Zachs-CanvaBook.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-a48e42a_1/share/nvim"

Run :checkhealth for more info
1.1.1%

**Comment by epwalsh** [comment] 2022-09-13 16:36
Hey @zachy-ho, this is odd, but I'm not familiar with Packer so maybe I'm missing something. Were there any error messages? If you call `:lua require("obsidian").setup({...})` directly from a vim session, any error messages then?

**Comment by zachy-ho** [comment] 2022-09-16 23:19
No error messages shown 🤔
I've decided to just use nvim for note taking instead of using Obsidian 😅

**Comment by epwalsh** [comment] 2022-09-20 18:32
Darn, sorry to hear that didn't work! I'll keep this open in case someone else is able to figure out what's going on.

**Comment by CamdenClark** [comment] 2022-09-21 04:52
I had the same issue until I _started_ nvim in the context of my registered nvim directory.

**Comment by pidgeon777** [comment] 2022-09-21 12:04
I'm on Windows 10 Pro and also have the same problem. The `ObsidianXXX` commands are not available. Also, I tested it when a **Markdown** file was selected.

**Comment by epwalsh** [comment] 2022-09-22 17:37
@pidgeon777 on Windows it could be an issue with paths. The suspect line is probably right here: https://github.com/epwalsh/obsidian.nvim/blob/e3d10fe6bf19f99e7ce289a13f0fc720c2cb276f/lua/obsidian/init.lua#L76

**Comment by epwalsh** [comment] 2022-09-23 00:03
As of https://github.com/epwalsh/obsidian.nvim/pull/17 this _might_ be fixed

**Comment by invidiae** [comment] 2022-10-02 15:15
I'm not sure if this is the same problem, but I am also not able to use the plugin using Packer.

@zachy-ho I think you are calling the plugin in a way that it gives you no error messages, even though it fails.

I get the following error message (on Linux):

    Error detected while processing /home/invidiae/.config/nvim/init.lua:
    E5113: Error while calling lua chunk: .../pack/packer/start/obsidian.nvim/lua/obsidian/config.lua:17: attempt to index field 'fs' (a nil value)
    stack traceback:
        .../pack/packer/start/obsidian.nvim/lua/obsidian/config.lua:17: in function 'default'
        .../pack/packer/start/obsidian.nvim/lua/obsidian/config.lua:30: in function 'normalize'
        ...te/pack/packer/start/obsidian.nvim/lua/obsidian/init.lua:48: in function 'setup'
        /home/invidiae/.config/nvim/init.lua:17: in main chunk

**Comment by epwalsh** [comment] 2022-10-02 20:31
@invidiae your error probably means you have an older version of neovim. This plugin uses the `vim.fs` built-in Lua module which wasn't introduced until nvim v0.8.0.

**Comment by gerryhernandez** [comment] 2023-01-08 21:24
I use Packer with this plugin without issue. Those of you experiencing this problem (@zachy-ho and @zachy-ho, especially), I'm happy to help, but I need more information because I can't reproduce the issue.

First, lets eliminate the simple stuff. Do a `:PackerClean` and `:PackerSync` and restart NeoVim. If we're lucky, that's it!

Unlucky? At this point, it'd be a huge help if you could post your nvim config, or at least the entire Packer section. Or if you can't post it, feel free to compare it against [mine](https://github.com/gerryhernandez/gdot/blob/main/.config/nvim/lua/g/plugins.lua#L139).

**Comment by epwalsh** [comment] 2023-11-23 00:32
Closing for now. Will reopen if anyone reports still having the issue.

**Closed by epwalsh** 2023-11-23 00:32 UTC
Labels: bug

**Comment by burgessa23** [comment] 2024-01-08 23:27
> I had the same issue until I _started_ nvim in the context of my registered nvim directory. I also had to be in a markdown buffer.

I just installed the plugin and am having this exact issue. 

`macOS 14.2.1`
`NVIM v0.10.0-dev-750+g642586977-Homebrew`

using lazy, my config is just a copy of what's in the README

**Comment by epwalsh** [comment] 2024-01-08 23:54
If your lazy.nvim config looks like this:

```lua
return {
  "epwalsh/obsidian.nvim",
  version = "*",
  lazy = true,
  ft = "markdown",
  dependencies = {
    "nvim-lua/plenary.nvim",
  },
  opts = {
    workspaces = {
      {
        name = "personal",
        path = "~/vaults/personal",
      },
    },
  },
}
```

Then the commands should become available whenever you open a markdown file, regardless of the location of the file or your current working directory. If that's not the case, then either:

1. There was an error within `require("obsidian").setup()`, in which case lazy.nvim will log the error.
2. Or lazy.nvim is not calling `require("obsidian").setup()` for some reason. One reason this could happen is if your filetype detection is not setup correctly.
