### ISSUE TITLE
bug: aliases got removed automatically and appended headings

### ISSUE THREAD

**Issue by aarnphm** [epwalsh/obsidian.nvim#381] opened 2024-02-09 08:34 UTC
### 🐛 Describe the bug

If you define `aliases` within your notes, the system will apparently append the first heading as one of the aliases.

<img width="327" alt="Screenshot 2024-02-09 at 03 33 25" src="https://github.com/epwalsh/obsidian.nvim/assets/29749331/483a2b35-2295-441f-98ac-f7b928704fa9">

This is unexpected, and there is no way to override this behaviour.

I suggest it either allows users to control through options or doesn't do this at all.

### Versions

nightly, version=false

**Comment by epwalsh** [comment] 2024-02-09 17:15
duplicate of #371

**Closed by epwalsh** 2024-02-09 17:15 UTC
Labels: bug
