### ISSUE TITLE
Neovim throws lua error when creating new wiki-links for files that don't exist yet.

### ISSUE THREAD

**Issue by GusJelly** [epwalsh/obsidian.nvim#507] opened 2024-03-22 16:18 UTC
### 🐛 Describe the bug

When I try to create a new file through a wiki-link from a note, neovim errors.
This does not happen when the file that I am linking to already exists. It only happens when I am linking to a non existent file through the create cmp autocompletion.

The error it shows looks like this:
```
E5108: Error executing lua ...al/share/nvim/lazy/obsidian.nvim/lua/obsidian/client.lua:283: attempt to call meth
od 'should_save_frontmatter' (a nil value)
stack traceback:
        ...al/share/nvim/lazy/obsidian.nvim/lua/obsidian/client.lua:283: in function 'should_save_frontmatter'
        ...al/share/nvim/lazy/obsidian.nvim/lua/obsidian/client.lua:1785: in function 'write_note'
        ...l/share/nvim/lazy/obsidian.nvim/lua/cmp_obsidian_new.lua:152: in function 'execute'
        ...stavo/.local/share/nvim/lazy/nvim-cmp/lua/cmp/source.lua:396: in function 'execute'
        ...ustavo/.local/share/nvim/lazy/nvim-cmp/lua/cmp/entry.lua:488: in function 'execute'
        ...gustavo/.local/share/nvim/lazy/nvim-cmp/lua/cmp/core.lua:503: in function <...gustavo/.local/share/nv
im/lazy/nvim-cmp/lua/cmp/core.lua:502>
        ...ocal/share/nvim/lazy/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function 'run'
        [string ":lua"]:1: in main chunk

```

Btw thank you for creating this wonderfull plugin. I got my life back on track thanks to this.

Thank you for the patience,
Gus.

### Config

```
-- Obsidian.nvim config
require("obsidian").setup({
    workspaces = {
        {
            name = "depracated",
            path = "~/notes-obsidian",
        },
        {
            name = "personal",
            path = "~/vaults/personal",
        },
        {
            name = "work",
            path = "~/vaults/work",
        },
    },

    disable_frontmatter = true,

    -- Optional, completion of wiki links, local markdown links, and tags using nvim-cmp.
    completion = {
        -- Set to false to disable completion.
        nvim_cmp = true,
        -- Trigger completion at 2 chars.
        min_chars = 2,
    },

    -- Optional, configure key mappings. These are the defaults. If you don't want to set any keymappings this
    -- way then set 'mappings = {}'.
    mappings = {
        -- Overrides the 'gf' mapping to work on markdown/wiki links within your vault.
        ["gd"] = {
            action = function()
                return require("obsidian").util.gf_passthrough()
            end,
            opts = { noremap = false, expr = true, buffer = true },
        },
        -- Toggle check-boxes.
        ["<leader>ch"] = {
            action = function()
                return require("obsidian").util.toggle_checkbox()
            end,
            opts = { buffer = true },
        },
    },

    -- Optional, customize how note IDs are generated given an optional title.
    ---@param title string|?
    ---@return string
    note_id_func = function(title)
        -- Create note IDs in a Zettelkasten format with a timestamp and a suffix.
        -- In this case a note with the title 'My new note' will be given an ID that looks
        -- like '1657296016-my-new-note', and therefore the file name '1657296016-my-new-note.md'
        local suffix = ""
        if title ~= nil then
            -- If title is given, transform it into valid file name.
            suffix = title:gsub(" ", "-"):gsub("[^A-Za-z0-9-]", ""):lower()
        else
            -- If title is nil, just add 4 random uppercase letters to the suffix.
            for _ = 1, 4 do
                suffix = suffix .. string.char(math.random(65, 90))
            end
        end
        return tostring(os.time()) .. "-" .. suffix
    end,
})
```

### Environment

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
Obsidian.nvim v3.7.4 (be075a1c8d290a383be755f0cb2411be5d065726)
Status:
  • buffer directory: nil
  • working directory: /home/gustavo
Workspaces:
  ✓ active workspace: Workspace(name='depracated', path='/home/gustavo/notes-obsidian', root='/home/gustavo/notes-obsidian')
  ✗ inactive workspace: Workspace(name='personal', path='/home/gustavo/dotfiles/vaults/personal', root='/home/gustavo/dotfiles/vaults/personal')
  ✗ inactive workspace: Workspace(name='work', path='/home/gustavo/dotfiles/vaults/work', root='/home/gustavo/dotfiles/vaults/work')
Dependencies:
  ✓ plenary.nvim: f7adfc4b3f4f91aab6caebf42b3682945fbc35be
  ✓ nvim-cmp: 6ed1c93465c33f6a53b4c3f103bf9d1ab696382a
Integrations:
  ✓ picker: TelescopePicker()
  ✓ completion: enabled (nvim-cmp) ✗ refs, ✗ tags, ✗ new
    all sources:
      • nvim_lsp
      • luasnip
      • path
Tools:
  ✓ rg: ripgrep 13.0.0
Environment:
  • operating system: Linux
Config:
  • notes_subdir: nil% 
```

**Comment by epwalsh** [comment] 2024-03-22 16:48
Hey @GusJelly, this is very odd! I'm not able to reproduce but I can help you debug. I created a new branch `GusJelly/debug` which will print out useful information before you hit that error. Could you try again on that branch and send me the output (check `:messages` or `:Noice` after you encounter the error)?

**Comment by iperry** [comment] 2024-03-22 18:56
Hi, encountering the same problem on Arch. I loaded your branch and got this trace:

```
{
  aliases = { "dfsafas" },
  id = "1711133664-HJMR",
  path = {
    filename = "/home/perry/syncthing/notes/personal/1711133664-HJMR.md"
  },
  tags = {},
  title = "dfsafas"
}
E5108: Error executing lua ...share/nvim/plugged/obsidian.nvim/lua/obsidian/client.lua:283: attempt to call method 'should_save_frontmatter' (a nil value)
stack traceback:
        ...share/nvim/plugged/obsidian.nvim/lua/obsidian/client.lua:283: in function 'should_save_frontmatter'
        ...share/nvim/plugged/obsidian.nvim/lua/obsidian/client.lua:1783: in function 'write_note'
        ...hare/nvim/plugged/obsidian.nvim/lua/cmp_obsidian_new.lua:152: in function 'execute'
        ...ry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/source.lua:396: in function 'execute'
        ...rry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/entry.lua:488: in function 'execute'
        ...erry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:503: in function <...erry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:502>
        ...l/share/nvim/plugged/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function 'run'
        [string ":lua"]:1: in main chunk
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```

**Comment by iperry** [comment] 2024-03-22 21:06
I bisected it back to commit daab7845def9a9ae719458e67e23f182849d84d5:
```
commit daab7845def9a9ae719458e67e23f182849d84d5 (HEAD)
Author: Pete <epwalsh10@gmail.com>
Date:   Sun Feb 25 12:45:28 2024 -0800

    API and internal improvements (#438)
    
    * API and internal improvements
    
    * don't put new notes in dailies folder
  ```

**Comment by epwalsh** [comment] 2024-03-22 22:23
Ahhh okay thank you all for the help! I think I know what's going on. Can someone try https://github.com/epwalsh/obsidian.nvim/pull/508 to verify that fixes it before I merge?

**Comment by iperry** [comment] 2024-03-22 22:46
> Ahhh okay thank you all for the help! I think I know what's going on. Can someone try #508 to verify that fixes it before I merge?

Didn't work for me. Checked out 176af19ce273d9b3475668e4731b3ac99c38c55a:
```
E5108: Error executing lua ...l/share/nvim/plugged/obsidian.nvim/lua/obsidian/note.lua:690: attempt to call method 'is_file' (a nil value)
stack traceback:
        ...l/share/nvim/plugged/obsidian.nvim/lua/obsidian/note.lua:690: in function 'save'
        ...share/nvim/plugged/obsidian.nvim/lua/obsidian/client.lua:1779: in function 'write_note'
        ...hare/nvim/plugged/obsidian.nvim/lua/cmp_obsidian_new.lua:161: in function 'execute'
        ...ry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/source.lua:396: in function 'execute'
        ...rry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/entry.lua:488: in function 'execute'
        ...erry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:503: in function <...erry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:502>
        ...l/share/nvim/plugged/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function 'run'
        [string ":lua"]:1: in main chunk
```

**Comment by iperry** [comment] 2024-03-22 22:49
Heres the same error with your debug print:
```
{
  aliases = { "fdsfads" },
  id = "1711147735-OULE",
  path = {
    filename = "/home/perry/syncthing/notes/personal/1711147735-OULE.md"
  },
  tags = {},
  title = "fdsfads",
  <metatable> = <1>{
    __eq = <function 1>,
    __index = {
      _is_frontmatter_boundary = <function 2>,
      add_alias = <function 3>,
      add_field = <function 4>,
      add_tag = <function 5>,
      as_tbl = <function 6>,
      display_info = <function 7>,
      display_name = <function 8>,
      exists = <function 9>,
      fname = <function 10>,
      from_buffer = <function 11>,
      from_file = <function 12>,
      from_file_async = <function 13>,
      from_file_with_contents_async = <function 14>,
      from_lines = <function 15>,
      frontmatter = <function 16>,
      frontmatter_lines = <function 17>,
      get_field = <function 18>,
      has_alias = <function 19>,
      has_tag = <function 20>,
      init = <function 21>,
      is_note_obj = <function 22>,
      mt = <table 1>,
      new = <function 23>,
      reference_ids = <function 24>,
      resolve_anchor_link = <function 25>,
      resolve_block = <function 26>,
      save = <function 27>,
      save_to_buffer = <function 28>,
      should_save_frontmatter = <function 29>
    },
    __tostring = <function 30>
  }
}
E5108: Error executing lua ...l/share/nvim/plugged/obsidian.nvim/lua/obsidian/note.lua:690: attempt to call method 'is_file' (a nil value)
stack traceback:
        ...l/share/nvim/plugged/obsidian.nvim/lua/obsidian/note.lua:690: in function 'save'
        ...share/nvim/plugged/obsidian.nvim/lua/obsidian/client.lua:1781: in function 'write_note'
        ...hare/nvim/plugged/obsidian.nvim/lua/cmp_obsidian_new.lua:161: in function 'execute'
        ...ry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/source.lua:396: in function 'execute'
        ...rry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/entry.lua:488: in function 'execute'
        ...erry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:503: in function <...erry/.local/share/nvim/plugged/nvim-cmp/lua/cmp/core.lua:502>
        ...l/share/nvim/plugged/nvim-cmp/lua/cmp/utils/feedkeys.lua:47: in function 'run'
        [string ":lua"]:1: in main chunk
```

**Comment by epwalsh** [comment] 2024-03-22 22:53
Ah, same issue for the path type. Just pushed a fix for that.

**Comment by iperry** [comment] 2024-03-22 22:59
462943f1391625740e616de0c29a4fa7ba765081 looks good to me!

**Closed** 2024-03-22 23:55 UTC
Labels: bug
